bro
tjorne/lifehack_spring_2024 pull request #2
Opened 2024-03-19 10:09 UTC by OttoDyva

2024-03-21 10:56 UTC, BekhanM approved these changes
wrong one dont click

2024-03-21 22:06 UTC, tjorne requested changes
Awesome project. 

There are some minor comments that should be addressed prior to this PR being approved and merged into production.

2024-03-21 22:06 UTC, tjorne commented on src/main/java/app/Main.java
> +
why the newlines?

2024-03-21 22:06 UTC, tjorne commented on src/main/java/app/Main.java
> +        app.get("/join", ctx -> ctx.render("jeopardy/join.html"));
why not add this to the JeopardyController.addRoutes()?

2024-03-21 22:06 UTC, tjorne commented on src/main/java/app/Main.java
> +
why the newlines?

2024-03-21 22:06 UTC, tjorne commented on src/main/resources/public/css/jeopardy.css
> +/*.task-table tr:nth-child(even) {
unused code - should this be added to production?

2024-03-21 22:06 UTC, tjorne commented on src/main/resources/public/css/styles.css
seems like it is only whitespace changes, but why are they here? 
I mean, it does look nicer than it did before, so perhaps one (or more) of you just had a case of OCD viewing this file? 😃

2024-03-21 22:06 UTC, tjorne commented on src/main/resources/templates/jeopardy/create.html
is this file ready to be added to production?

2024-03-24 08:18 UTC, tjorne approved these changes

2024-03-24 08:18 UTC, merged