Smm
tjorne/lifehack_spring_2024 pull request #20
Opened 2024-03-21 18:46 UTC by sanderMarcusChristensen

Vores mega seje, helt nye Quote Generator

2024-03-21 20:11 UTC, tjorne commented
Overall looks great. 

Would have approved the PR if not for missing sql for creating and inserting data to the quotes table.

2024-03-21 20:13 UTC, tjorne requested changes

2024-03-21 20:13 UTC, tjorne commented on src/main/resources/templates/timezones/index.html
Why these changes to this file? 
Are you testing to see if I'd notice? 😃 

Please revert changes to this file.

2024-03-21 20:13 UTC, tjorne commented on src/main/resources/public/css/timezones.css
Are these two newlines really necessary?

2024-03-21 20:13 UTC, tjorne commented on src/main/resources/public/css/styles.css
Are these two newlines really necessary?

2024-03-22 09:01 UTC, sanderMarcusChristensen reviewed
fixed now

2024-03-24 07:47 UTC, tjorne approved these changes

2024-03-24 07:47 UTC, merged